# Generated by Django 4.2.5 on 2023-09-10 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='blog/image')),
                ('date', models.DateField()),
                ('date_time', models.DateTimeField()),
                ('time_1', models.TimeField()),
                ('number', models.BigIntegerField()),
                ('number_1', models.DecimalField(decimal_places=2, max_digits=5)),
                ('time_2', models.DurationField()),
                ('number_2', models.FloatField()),
                ('number_3', models.IntegerField()),
                ('number_4', models.PositiveBigIntegerField()),
                ('number_5', models.PositiveIntegerField()),
                ('number_6', models.PositiveSmallIntegerField()),
                ('number_7', models.SmallIntegerField()),
                ('text', models.SlugField()),
                ('e_mail', models.EmailField(max_length=254)),
                ('car', models.BooleanField()),
                ('text_1', models.BinaryField()),
                ('I_P', models.GenericIPAddressField()),
            ],
        ),
    ]
